sudo: false

language: php

php:
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
  - php: 7.1
    env: WP_TRAVISCI=travis:jshint
  allow_failures:
  fast_finish: true

cache:
  apt: true
  bundler: true
  directories:
  - vendor
  - $HOME/.composer/cache
  - node_modules

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
    composer global require phpmd/phpmd
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    composer install --no-interaction
  - |
    if [[ "$WP_TRAVISCI" == "travis:jshint" ]] ; then
      npm install
      node --version
      npm --version
      grunt --version
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "travis:phpvalidate" ]] ; then
      grunt checktextdomain
      phpmd classes text codesize,naming,unusedcode
      phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
    fi
  - |
    if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
      phpunit --coverage-clover build/logs/clover.xml
    else
      phpunit
    fi
  - |
   if [[ "$WP_TRAVISCI" == "travis:jshint" ]] ; then
     grunt jshint
   fi
    
 deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
